"use client";

import { useEffect, useState, type FormEvent } from "react";
import LoadingScreen from "@/components/common/loading-screen";
import StatCard from "@/components/dashboard/stat-card";
import { apiFetch } from "@/lib/api";
import { formatCurrency, labelize } from "@/lib/format";
import type { ProfitLossReport } from "@/types";

type OrdersReport = { byStatus: Array<{ _id: string; orders: number; revenue: number; profit: number }>; bySource: Array<{ _id: string; orders: number; revenue: number }>; topCities: Array<{ _id: string; orders: number; revenue: number }> };
type CourierReport = { booked: number; delivered: number; rto: number; cod: number; unsettledCod: number; courierCharges: number; deliveryRate: number; rtoRate: number };

export default function ReportsPage() {
  const [range, setRange] = useState({ from: new Date(new Date().getFullYear(), new Date().getMonth(), 1).toISOString().slice(0, 10), to: new Date().toISOString().slice(0, 10) });
  const [profit, setProfit] = useState<ProfitLossReport | null>(null); const [orders, setOrders] = useState<OrdersReport | null>(null); const [courier, setCourier] = useState<CourierReport | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  async function load() { setLoading(true); setError(""); try { const query = `?from=${range.from}&to=${range.to}`; const [profitData, orderData, courierData] = await Promise.all([apiFetch<{ success: true; report: ProfitLossReport }>(`/reports/profit-loss${query}`), apiFetch<{ success: true; report: OrdersReport }>(`/reports/orders${query}`), apiFetch<{ success: true; report: CourierReport }>(`/reports/courier${query}`)]); setProfit(profitData.report); setOrders(orderData.report); setCourier(courierData.report); } catch (e) { setError((e as Error).message); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  function submit(event: FormEvent) { event.preventDefault(); void load(); }
  if (loading && !profit) return <LoadingScreen message="Generating reports..." />;
  return <main className="page"><div className="page-header"><div><h1>Reports</h1><p className="muted">Profit and loss, order sources, city performance and courier efficiency.</p></div><form className="inline-filter" onSubmit={submit}><input className="input" type="date" value={range.from} onChange={(e) => setRange({ ...range, from: e.target.value })} /><input className="input" type="date" value={range.to} onChange={(e) => setRange({ ...range, to: e.target.value })} /><button className="button">Apply</button></form></div>{error ? <div className="error-box page-message">{error}</div> : null}
    <section className="stats-grid"><StatCard label="Delivered Revenue" value={formatCurrency(profit?.deliveredRevenue ?? 0)} note={`${profit?.deliveredOrders ?? 0} realized orders`} /><StatCard label="Gross Profit" value={formatCurrency(profit?.grossProfit ?? 0)} note={`Direct cost ${formatCurrency(profit?.directOrderCost ?? 0)}`} /><StatCard label="General + Ads" value={formatCurrency((profit?.generalExpenses ?? 0) + (profit?.advertisementSpend ?? 0))} note="Period overhead" /><StatCard label="Net Profit" value={formatCurrency(profit?.netProfit ?? 0)} note={`${profit?.returnCount ?? 0} returns/RTO`} /></section>
    <section className="content-grid"><article className="card card-padding"><h2 className="section-title">P&L breakdown</h2><div className="calculation-list"><div><span>Delivered revenue</span><strong>{formatCurrency(profit?.deliveredRevenue ?? 0)}</strong></div><div><span>Direct order cost</span><strong>- {formatCurrency(profit?.directOrderCost ?? 0)}</strong></div><div><span>Returned/RTO order cost</span><strong>- {formatCurrency(profit?.failedOrderCost ?? 0)}</strong></div><div><span>General expenses</span><strong>- {formatCurrency(profit?.generalExpenses ?? 0)}</strong></div><div><span>Advertisement spend</span><strong>- {formatCurrency(profit?.advertisementSpend ?? 0)}</strong></div><div><span>Customer refunds</span><strong>- {formatCurrency(profit?.customerRefunds ?? 0)}</strong></div><div className="calculation-total"><span>Net profit</span><strong>{formatCurrency(profit?.netProfit ?? 0)}</strong></div></div></article>
      <aside className="card card-padding"><h2 className="section-title">Courier efficiency</h2><div className="calculation-list"><div><span>Booked</span><strong>{courier?.booked ?? 0}</strong></div><div><span>Delivered</span><strong>{courier?.delivered ?? 0}</strong></div><div><span>RTO</span><strong>{courier?.rto ?? 0}</strong></div><div><span>Delivery rate</span><strong>{courier?.deliveryRate ?? 0}%</strong></div><div><span>RTO rate</span><strong>{courier?.rtoRate ?? 0}%</strong></div><div><span>Unsettled COD</span><strong>{formatCurrency(courier?.unsettledCod ?? 0)}</strong></div></div></aside></section>
    <section className="content-grid"><article className="card"><div className="card-padding"><h2 className="section-title">Orders by status</h2></div><div className="table-wrap"><table className="table"><thead><tr><th>Status</th><th>Orders</th><th>Revenue</th><th>Profit</th></tr></thead><tbody>{orders?.byStatus.map((row) => <tr key={row._id}><td>{labelize(row._id)}</td><td>{row.orders}</td><td>{formatCurrency(row.revenue)}</td><td>{formatCurrency(row.profit)}</td></tr>)}</tbody></table></div></article><article className="card"><div className="card-padding"><h2 className="section-title">Orders by source</h2></div><div className="table-wrap"><table className="table"><thead><tr><th>Source</th><th>Orders</th><th>Revenue</th></tr></thead><tbody>{orders?.bySource.map((row) => <tr key={row._id}><td>{labelize(row._id)}</td><td>{row.orders}</td><td>{formatCurrency(row.revenue)}</td></tr>)}</tbody></table></div></article></section>
    <section className="card users-table-card"><div className="card-padding"><h2 className="section-title">Top cities</h2></div><div className="table-wrap"><table className="table"><thead><tr><th>City</th><th>Orders</th><th>Revenue</th></tr></thead><tbody>{orders?.topCities.map((row) => <tr key={row._id}><td>{row._id || "Unknown"}</td><td>{row.orders}</td><td>{formatCurrency(row.revenue)}</td></tr>)}</tbody></table></div></section>
  </main>;
}
