"use client";

import { useEffect, useState, type FormEvent } from "react";
import LoadingScreen from "@/components/common/loading-screen";
import StatCard from "@/components/dashboard/stat-card";
import { apiFetch } from "@/lib/api";
import { formatCurrency, formatDate, labelize } from "@/lib/format";
import type { CashBalance, CashTransaction, LedgerTransaction, PartnerSummary, ProfitDistribution } from "@/types";

const transactionInitial = { transactionDate: new Date().toISOString().slice(0, 10), partnerCode: "PARTNER_A", type: "CAPITAL_CONTRIBUTION", amount: 0, description: "", businessAccount: "CASH", direction: "CREDIT" };
const distributionInitial = { periodStart: new Date(new Date().getFullYear(), new Date().getMonth(), 1).toISOString().slice(0, 10), periodEnd: new Date().toISOString().slice(0, 10), reserveAmount: 0, notes: "" };
export default function PartnersPage() {
  const [summary, setSummary] = useState<PartnerSummary | null>(null); const [ownership, setOwnership] = useState({ partnerAPercent: 50, partnerBPercent: 50 }); const [ledger, setLedger] = useState<LedgerTransaction[]>([]); const [balances, setBalances] = useState<CashBalance[]>([]); const [cash, setCash] = useState<CashTransaction[]>([]); const [distributions, setDistributions] = useState<ProfitDistribution[]>([]); const [transactionForm, setTransactionForm] = useState(transactionInitial); const [distributionForm, setDistributionForm] = useState(distributionInitial); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  async function load() { try { const [summaryData, ledgerData, cashData, distributionData] = await Promise.all([apiFetch<{ success: true; ownership: typeof ownership; summary: PartnerSummary }>("/partners/summary"), apiFetch<{ success: true; transactions: LedgerTransaction[] }>("/partners/ledger"), apiFetch<{ success: true; balances: CashBalance[]; transactions: CashTransaction[] }>("/partners/cash"), apiFetch<{ success: true; distributions: ProfitDistribution[] }>("/partners/profit-distributions")]); setSummary(summaryData.summary); setOwnership(summaryData.ownership); setLedger(ledgerData.transactions); setBalances(cashData.balances); setCash(cashData.transactions); setDistributions(distributionData.distributions); } catch (e) { setError((e as Error).message); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  async function addTransaction(event: FormEvent) { event.preventDefault(); try { const result = await apiFetch<{ success: true; message: string }>("/partners/ledger", { method: "POST", body: JSON.stringify(transactionForm) }); setMessage(result.message); setTransactionForm(transactionInitial); await load(); } catch (e) { setError((e as Error).message); } }
  async function distribute(event: FormEvent) { event.preventDefault(); try { const result = await apiFetch<{ success: true; message: string }>("/partners/profit-distributions", { method: "POST", body: JSON.stringify(distributionForm) }); setMessage(result.message); await load(); } catch (e) { setError((e as Error).message); } }
  if (loading) return <LoadingScreen message="Loading partner accounts..." />;
  return <main className="page"><div className="page-header"><div><h1>Partners & Wallets</h1><p className="muted">50/50 funding, reimbursements, withdrawals, profit allocation and cash balances.</p></div><span className="badge">{ownership.partnerAPercent}/{ownership.partnerBPercent}</span></div>{error ? <div className="error-box page-message">{error}</div> : null}{message ? <div className="success-box page-message">{message}</div> : null}
    <section className="stats-grid"><StatCard label="Partner A Balance" value={formatCurrency(summary?.partnerA.settlementBalance ?? 0)} note={(summary?.partnerA.settlementBalance ?? 0) >= 0 ? "Business/partner owes A" : "A must contribute"} /><StatCard label="Partner B Balance" value={formatCurrency(summary?.partnerB.settlementBalance ?? 0)} note={(summary?.partnerB.settlementBalance ?? 0) >= 0 ? "Business/partner owes B" : "B must contribute"} /><StatCard label="Net Partner Funding" value={formatCurrency(summary?.totalFunding ?? 0)} note="Credits less reimbursements" /><StatCard label="Cash + Digital" value={formatCurrency(balances.filter((item) => item.account !== "COURIER_RECEIVABLE").reduce((sum, item) => sum + item.balance, 0))} note={`COD receivable ${formatCurrency(balances.find((item) => item.account === "COURIER_RECEIVABLE")?.balance ?? 0)}`} /></section>
    <section className="content-grid"><article className="card card-padding"><h2 className="section-title">Partner transaction</h2><form className="form" onSubmit={addTransaction}><div className="two-column-form"><div className="field"><label>Date</label><input className="input" type="date" value={transactionForm.transactionDate} onChange={(e) => setTransactionForm({ ...transactionForm, transactionDate: e.target.value })} /></div><div className="field"><label>Partner</label><select className="select" value={transactionForm.partnerCode} onChange={(e) => setTransactionForm({ ...transactionForm, partnerCode: e.target.value })}><option>PARTNER_A</option><option>PARTNER_B</option></select></div><div className="field"><label>Type</label><select className="select" value={transactionForm.type} onChange={(e) => setTransactionForm({ ...transactionForm, type: e.target.value })}>{["CAPITAL_CONTRIBUTION","REIMBURSEMENT","PARTNER_WITHDRAWAL","SETTLEMENT_ADJUSTMENT"].map((item) => <option key={item}>{item}</option>)}</select></div><div className="field"><label>Business account</label><select className="select" value={transactionForm.businessAccount} onChange={(e) => setTransactionForm({ ...transactionForm, businessAccount: e.target.value })}><option value="">None / direct partner settlement</option>{["CASH","BANK","EASYPAISA","JAZZCASH"].map((item) => <option key={item}>{item}</option>)}</select></div><div className="field"><label>Ledger direction</label><select className="select" value={transactionForm.direction} onChange={(e) => setTransactionForm({ ...transactionForm, direction: e.target.value })}><option value="CREDIT">Credit partner</option><option value="DEBIT">Debit partner</option></select></div><div className="field"><label>Amount</label><input className="input" min="0.01" type="number" value={transactionForm.amount} onChange={(e) => setTransactionForm({ ...transactionForm, amount: Number(e.target.value) })} /></div><div className="field"><label>Description</label><input className="input" required value={transactionForm.description} onChange={(e) => setTransactionForm({ ...transactionForm, description: e.target.value })} /></div></div><div className="actions-row"><button className="button">Record transaction</button></div></form></article>
      <aside className="card card-padding"><h2 className="section-title">Profit distribution</h2><form className="form" onSubmit={distribute}><div className="field"><label>Period start</label><input className="input" type="date" value={distributionForm.periodStart} onChange={(e) => setDistributionForm({ ...distributionForm, periodStart: e.target.value })} /></div><div className="field"><label>Period end</label><input className="input" type="date" value={distributionForm.periodEnd} onChange={(e) => setDistributionForm({ ...distributionForm, periodEnd: e.target.value })} /></div><div className="field"><label>Business reserve</label><input className="input" min="0" type="number" value={distributionForm.reserveAmount} onChange={(e) => setDistributionForm({ ...distributionForm, reserveAmount: Number(e.target.value) })} /></div><button className="button">Allocate profit</button></form></aside></section>
    <section className="card users-table-card"><div className="table-wrap"><table className="table"><thead><tr><th>Transaction</th><th>Date</th><th>Partner</th><th>Type</th><th>Description</th><th>Direction</th><th>Amount</th></tr></thead><tbody>{ledger.map((item) => <tr key={item.id}><td className="code-text">{item.transactionNumber}</td><td>{formatDate(item.transactionDate)}</td><td>{labelize(item.partnerCode)}</td><td>{labelize(item.type)}</td><td>{item.description}</td><td>{item.direction}</td><td className={item.signedAmount >= 0 ? "positive-text" : "negative-text"}>{formatCurrency(item.signedAmount)}</td></tr>)}{!ledger.length ? <tr><td className="empty-state" colSpan={7}>No partner ledger entries.</td></tr> : null}</tbody></table></div></section>
    <section className="card users-table-card"><div className="card-padding"><h2 className="section-title">Profit distributions</h2></div><div className="table-wrap"><table className="table"><thead><tr><th>Distribution</th><th>Period</th><th>Net Profit</th><th>Reserve</th><th>Partner A</th><th>Partner B</th></tr></thead><tbody>{distributions.map((item) => <tr key={item.id}><td className="code-text">{item.distributionNumber}</td><td>{formatDate(item.periodStart)} – {formatDate(item.periodEnd)}</td><td>{formatCurrency(item.netProfit)}</td><td>{formatCurrency(item.reserveAmount)}</td><td>{formatCurrency(item.partnerAShare)}</td><td>{formatCurrency(item.partnerBShare)}</td></tr>)}{!distributions.length ? <tr><td className="empty-state" colSpan={6}>No profit distributions.</td></tr> : null}</tbody></table></div></section>
    <details className="card card-padding top-gap"><summary><strong>Cash transaction history ({cash.length})</strong></summary><div className="table-wrap top-gap"><table className="table"><thead><tr><th>Ref</th><th>Account</th><th>Source</th><th>Description</th><th>Amount</th></tr></thead><tbody>{cash.map((item) => <tr key={item.id}><td className="code-text">{item.transactionNumber}</td><td>{item.account}</td><td>{item.sourceType}</td><td>{item.description}</td><td>{formatCurrency(item.signedAmount)}</td></tr>)}</tbody></table></div></details>
  </main>;
}
